### ISSUE TITLE
Not able to extract The Adventure Works  2017 Excel file

### ISSUE THREAD

**Issue by fahad1512** [PacktPublishing/Expert-Data-Modeling-with-Power-BI#1]
I was trying to Extract the AdventureWorks2017.zip file but the files seems to be corrupt. 

![image](https://user-images.githubusercontent.com/78873451/123672314-6750a180-d7fc-11eb-9402-939a24d451ca.png)

**Comment by soheildataviz** [comment]
Hi @fahad1512,

You must download both **AdventureWorksDW2017.zip.001** and **AdventureWorksDW2017.zip.002** from the **[AdventureWorksDW2017(xlsx)](https://github.com/PacktPublishing/Expert-Data-Modeling-with-Power-BI/tree/master/AdventureWorksDW2017(xlsx))** folder. 
Make sure you store both files in the same folder, then use the **AdventureWorksDW2017.zip.001** file to unzip the package.

![image](https://user-images.githubusercontent.com/58403397/125177118-66246900-e22d-11eb-8297-87237e384318.png)

Thanks,
Soheil
